import React from 'react';
import { X } from 'lucide-react';
import {
  CASHFLOW_CATEGORIES, CASHFLOW_GROUPS, categoryLabel,
} from '../../../../supabase/functions/_shared/taxonomy/cashflow';
import { assetTypeLabel } from '../../../../supabase/functions/_shared/taxonomy/balance';

// Small UI atoms shared between the plan (StandingItemsPanel) and the actuals
// (ActualsPanel) halves of the cashflow tab, plus CashflowTab.tsx itself —
// pulled out so the grouped category picker, month formatting and modal shell
// are defined exactly once instead of drifting between the two screens.

export const fmt = (n: number) => n.toLocaleString('en-MY', { minimumFractionDigits: 0, maximumFractionDigits: 0 });

/**
 * Like `fmt`, but keeps cents when the figure actually has them — the
 * cash-flow waterfall (CashflowTab.tsx) shows exact take-home/savable/net
 * figures (e.g. RM 2,275.15), which the whole-ringgit `fmt` above would
 * silently round away. Whole numbers still print with no decimals.
 */
export function fmt2(n: number): string {
  const rounded = Math.round((n + Number.EPSILON) * 100) / 100;
  const hasCents = Math.abs(rounded - Math.round(rounded)) > 1e-9;
  return rounded.toLocaleString('en-MY', {
    minimumFractionDigits: hasCents ? 2 : 0,
    maximumFractionDigits: 2,
  });
}

export const inp = 'w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-xin-gold';

export const Loader = () => <div className="flex items-center justify-center h-40"><div className="animate-spin rounded-full h-7 w-7 border-b-2 border-xin-blue" /></div>;

export const Fr = ({ label, children }: { label: string; children: React.ReactNode }) => (
  <div className="mb-3">
    <label className="block text-xs font-medium text-slate-400 mb-1">{label}</label>
    {children}
  </div>
);

export const Modal = ({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) => (
  <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
    <div className="bg-white rounded-2xl p-6 w-full max-w-sm max-h-[90vh] overflow-y-auto shadow-xl">
      <div className="flex items-center justify-between mb-5">
        <h3 className="font-semibold text-xin-blue">{title}</h3>
        <button onClick={onClose} className="text-slate-300 hover:text-slate-500"><X size={18} /></button>
      </div>
      {children}
    </div>
  </div>
);

export const MONTH_LABELS = ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'];
export const MONTH_LABELS_EN = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export function monthName(m: number, language: string): string {
  return (language === 'zh' ? MONTH_LABELS : MONTH_LABELS_EN)[m - 1] ?? String(m);
}

/** YYYY-MM-01 for a year/month pair — the shape period_month / effective_from
 *  expect. */
export function toPeriodMonth(year: number, month: number): string {
  return `${year}-${String(month).padStart(2, '0')}-01`;
}

/** The current month as 'YYYY-MM', the value a native <input type="month">
 *  wants and returns. */
export function currentMonthInput(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
}

// Frequencies offered on the ACTUALS ("this month's real figure") form —
// unchanged from before P2b, so existing month-by-month behaviour is not
// disturbed.
export const ENTRY_FREQ: [string, string][] = [
  ['monthly', 'Monthly'], ['annual', 'Annual'], ['quarterly', 'Quarterly'],
  ['semi_annual', 'Semi-annual'], ['one_off', 'One-off'],
];

// Frequencies offered on a STANDING ITEM (plan) — 决策 4 adds weekly, which
// actuals rows have never used.
export const ITEM_FREQUENCIES: Array<[value: string, en: string, zh: string]> = [
  ['monthly', 'Monthly', '按月'],
  ['quarterly', 'Quarterly', '按季度'],
  ['semi_annual', 'Semi-annual', '半年一次'],
  ['annual', 'Annual', '按年'],
  ['one_off', 'One-off', '一次性'],
  ['weekly', 'Weekly', '按周'],
];

export function freqLabel(freq: string, lang: 'en' | 'zh'): string {
  const row = ITEM_FREQUENCIES.find((r) => r[0] === freq);
  if (row) return lang === 'zh' ? row[2] : row[1];
  return freq;
}

/**
 * Grouped by the chart of accounts (I1–I4 / O1–O10). A legacy code that is no
 * longer offered still shows as the current value, so opening an old row
 * never silently re-files it.
 *
 * `excludeAutoGenerated` drops categories the taxonomy marks `auto_generated`
 * (installments, premiums, employer/employee EPF, SOCSO/EIS — 决策 7/A: those
 * come from a liability, policy or the statutory calculator, never a
 * hand-picked item) from the OFFERED list. The bound value is still shown
 * even if it falls in that set, so an existing row never disappears.
 */
export function CategorySelect({ direction, value, onChange, language, allowEmpty, excludeAutoGenerated }: {
  direction: 'inflow' | 'outflow'; value: string; onChange: (v: string) => void; language: string;
  allowEmpty?: boolean; excludeAutoGenerated?: boolean;
}) {
  const zh = language === 'zh';
  const known = CASHFLOW_CATEGORIES.some((c) => c.code === value);
  return (
    <select value={value} onChange={(e) => onChange(e.target.value)} className={inp}>
      {allowEmpty && <option value="">—</option>}
      {value && !known && <option value={value}>{categoryLabel(value, zh ? 'zh' : 'en')} ({value})</option>}
      {CASHFLOW_GROUPS.filter((g) => g.direction === direction).map((g) => {
        const options = CASHFLOW_CATEGORIES.filter((c) => c.group === g.id && (!excludeAutoGenerated || !c.auto_generated || c.code === value));
        if (options.length === 0) return null;
        return (
          <optgroup key={g.id} label={`${g.id} · ${zh ? g.label_zh : g.label_en}`}>
            {options.map((c) => (
              <option key={c.code} value={c.code}>{zh ? c.label_zh : c.label_en}</option>
            ))}
          </optgroup>
        );
      })}
    </select>
  );
}

export interface AssetOption {
  id: string;
  name: string;
  asset_type: string;
}

/** The optional "关联资产" picker on the item form — 决策 7. */
export function AssetSelect({ assets, value, onChange, language }: {
  assets: AssetOption[]; value: string; onChange: (v: string) => void; language: string;
}) {
  const zh = language === 'zh';
  return (
    <select value={value} onChange={(e) => onChange(e.target.value)} className={inp}>
      <option value="">—</option>
      {assets.map((a) => (
        <option key={a.id} value={a.id}>{a.name} ({assetTypeLabel(a.asset_type, zh ? 'zh' : 'en')})</option>
      ))}
    </select>
  );
}
