// pdf/sampleData.ts
// Fictional sample data for calibration proofs — never use real client data.
import { initialPrsFormData, type PrsFormData } from '../types/prs';

export const samplePrsData: PrsFormData = {
  ...initialPrsFormData,
  applicant_type: 'new',
  applicant_category: 'personal',
  salutation: 'Mr',
  full_name: 'Ahmad Sample Bin Test',
  nric: '900101-14-5678',
  date_of_birth: '1990-01-01',
  gender: 'male',
  race: 'chinese',
  nationality: 'Malaysian',
  marital_status: 'married',
  mothers_maiden_name: 'Lim Test',
  occupation_category: 'executive',
  nature_of_occupation: 'finance_insurance_property',
  employer_name: 'SAMPLE SDN BHD',
  monthly_income_bracket: '8001_15000',
  phone_mobile: '0123456789',
  email: 'sample@example.com',
  corr_address: '88 JALAN SAMPLE 1/2, TAMAN UJIAN',
  corr_postcode: '47000',
  corr_city: 'PETALING JAYA',
  corr_state: 'Selangor',
  source_of_funds: 'employment',
  purpose: 'retirement',
  pep_status: 'no',
  contribution_amount: '3000',
  contribution_direction: 'do_it_for_me',
  difm_scheme: 'prs_plus',
  epf_account_number: '12345678',
  bank_name: 'MAYBANK',
  bank_account_number: '1122334455667',
  tax_residency: 'resident',
  tin_number: 'IG12345678090',
  place_of_birth: 'KUALA LUMPUR',
  country_of_birth: 'MALAYSIA',
  crs_tax_residences: [
    { country: 'MALAYSIA', tin: 'IG12345678090', noTinReason: '', reasonBExplanation: '' },
    { country: '', tin: '', noTinReason: '', reasonBExplanation: '' },
    { country: '', tin: '', noTinReason: '', reasonBExplanation: '' },
  ],
  religion_islam: 'non_muslim',
  nominees: [
    { name: 'SITI SAMPLE BINTI TEST', nric: '920202-14-1234', mobile: '0198765432', email: 'siti@example.com', percentage: '60' },
    { name: 'ALI SAMPLE BIN TEST', nric: '150303-14-9876', mobile: '', email: '', percentage: '40' },
    ...Array.from({ length: 4 }, () => ({ name: '', nric: '', mobile: '', email: '', percentage: '' })),
  ],
  isa_mode: 'new',
  isa_education: 'degree_above',
  isa_disposable_income: '8001_15000',
  isa_commitment: '2001_5000',
  isa_invest_pct: '11_20',
  isa_expectation: 'capital_growth',
  isa_purpose: 'retirement',
  isa_reasons: ['meet_objective'],
  isa_exp_unit_trust: '5',
  isa_q1_age: '3', isa_q2_experience: '3', isa_q3_understanding: '3',
  isa_q4_objective: '3', isa_q5_duration: '5', isa_q6_risk: '3',
  isa_vulnerable: ['none'],
  isa_acks: ['yes', 'yes', 'yes', 'no', 'no'],
  utc_recommended_category: 'moderate',
  utc_basis: ['risk_profile', 'objectives_horizon'],
  utc_funds: ['PRINCIPAL PRS PLUS MODERATE FUND', 'PRINCIPAL PRS PLUS CONSERVATIVE FUND', '', '', ''],
  topup_type: 'topup',
  consultant_name: 'LEON LEE',
  consultant_code: 'CON1234',
  branch_name_code: 'KL MAIN / 001',
  channel: 'prs_consultant',
  sign_date: '2026-06-15',
};
