import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.welcome': 'Welcome',
    'nav.basic': 'Basic Information',
    'nav.income': 'Income',
    'nav.assets': 'Assets',
    'nav.liabilities': 'Liabilities',
    'nav.expenses': 'Expenses',
    'nav.investments': 'Investments',
    'nav.review': 'Review Summary',
    'header.services': 'Financial Advisory Services',
    'welcome.title': 'Welcome to XinWealth',
    'welcome.subtitle': 'To provide you with the best financial advice, we need to understand your current situation.',
    'welcome.button': 'Get Started',
    'pdpa.title': 'PDPA Consent',
    'pdpa.content': 'By proceeding, you agree that your personal data will be collected, processed, and stored in accordance with the Personal Data Protection Act (PDPA).',
    'pdpa.disclaimer': "Don't worry, your data is completely secure and will only be used for the purpose of financial advisory.",
    'pdpa.accept': 'I Agree & Continue',
    
    'basic.title': 'About You',
    'basic.name': 'Full Name',
    'basic.salutation': 'Salutation',
    'basic.email': 'Email',
    'basic.dob': 'Date of Birth',
    'basic.nationality': 'Nationality',
    'basic.residency': 'Residency',
    'basic.marital': 'Marital Status',
    'basic.retirement': 'Desired Retirement Age',
    'basic.employment': 'Employment Status',
    'basic.tax': 'Tax Status',
    'basic.occupation': 'Occupation',
    'basic.continue': 'Continue',
    'basic.back': 'Back',

    'income.title': 'Our Income',
    'income.active': 'Active Income',
    'income.monthly': 'Monthly Gross Salary',
    'income.salaryLabel': 'I am earning a gross monthly salary of:',
    'income.bonus': 'Annual Bonus',
    'income.bonusLabel': 'My Annual Bonus is',
    'income.passive': 'Passive Income',
    'income.rental': 'Rental Income',
    'income.rentalOpt': 'I own a rental property',
    'income.dividend': 'Dividend Income',
    'income.dividendOpt': 'I own dividends',
    'income.other': 'Other Income',
    'income.otherOpt': 'Other Income Type',
    'income.add': 'Add',
    'income.addBtn': 'Add Income',
    'income.addMore': 'Add Another Income',
    'income.amount': 'Amount',
    'income.desc': 'Description',
    
    'assets.title': 'Our Assets',
    'assets.liquid': 'My Savings',
    'assets.savings': 'My Savings is valued at',
    'assets.epf': 'EPF',
    'assets.epf.account1': 'Account 1 (Akaun Persaraan)',
    'assets.epf.account2': 'Account 2 (Akaun Sejahtera)',
    'assets.epf.account3': 'Account 3 (Akaun Fleksibel)',
    'assets.selectAll': 'Select all that applies',
    'assets.properties': 'I own a property',
    'assets.vehicles': 'I own a vehicle',
    'assets.others': 'Other Assets',
    'assets.add': 'Add Asset',
    'assets.addBtn': 'Add Asset',
    'assets.value': 'Value',

    'liabilities.title': 'My Liabilities',
    'liabilities.mortgages': 'Mortgage Loan',
    'liabilities.car': 'Car Loan',
    'liabilities.study': 'Study Loan',
    'liabilities.interest': 'Interest Only Loan',
    'liabilities.renovation': 'Renovation Loan',
    'liabilities.others': 'Other Loans',
    'liabilities.add': 'Add Loan',
    'liabilities.addBtn': 'Add Loan',
    'liabilities.balance': 'Outstanding Balance',

    'expenses.title': 'Our Expenses',
    'expenses.household': 'Household',
    'expenses.transport': 'Transportation',
    'expenses.dependants': 'Dependants',
    'expenses.personal': 'Personal',
    'expenses.misc': 'Miscellaneous',
    'expenses.others': 'Other Expenses',
    'expenses.add': 'Add Expense',
    'expenses.type': 'Type',
    'expenses.info': 'If loan details have been provided earlier, loan payments will be auto-generated and do not need to be entered again as expenses.',

    'investments.title': 'My Investments',
    'investments.etf': 'Exchange Traded Funds',
    'investments.bonds': 'Bonds',
    'investments.stocks': 'Stocks & Shares',
    'investments.unit': 'Unit Trusts',
    'investments.unitTrusts': 'Unit Trusts',
    'investments.fd': 'Fixed Deposits',
    'investments.fixedDeposits': 'Fixed Deposits',
    'investments.forex': 'Foreign Exchange',
    'investments.money': 'Money Market',
    'investments.others': 'Other Investment',
    'investments.other': 'Other Investment',
    'investments.add': 'Add Investment',
    'investments.addBtn': 'Add Investment',

    'review.title': 'Review Summary',
    'review.subtitle': "Let's check if everything is correct before you submit!",
    'review.profile': 'Profile',
    'review.income': 'Income',
    'review.assets': 'Assets',
    'review.liabilities': 'Liabilities',
    'review.expenses': 'Expenses',
    'review.investments': 'Investments',
    'review.edit': '[Edit Details]',
    'review.editDetails': '[Edit Details]',
    'review.total': 'TOTAL',
    'review.gross': 'Gross Income',
    'review.grossIncome': 'Gross Income',
    'review.bonus': 'Bonus',
    'review.nodata': 'No data available.',
    'review.noData': 'No data available.',
    'review.hiddenLabel': 'Detailed {0} are not displayed to save space. Click Edit to view.',
    'review.hiddenDetails': 'Detailed data is not displayed to save space. Click Edit to view.',
    'review.confirm': 'Confirm',
    
    'common.required': 'Required',
    'common.max100': 'Maximum 100 characters',
    'common.maxChars': 'Maximum 100 characters',
    'common.rm': 'RM',
    'common.month': '/month',
    'common.year': '/year',
    'common.perMonth': '/month',
    'common.perYear': '/year',
    'common.delete': 'Delete',
    'common.value': 'Value',
    'common.description': 'Description',
    'common.expand': 'Expand',
    'common.collapse': 'Collapse',
    'common.selectAll': 'Select all that applies'
  },
  zh: {
    'nav.welcome': '欢迎',
    'nav.basic': '基本信息',
    'nav.income': '收入',
    'nav.assets': '资产',
    'nav.liabilities': '负债',
    'nav.expenses': '开销',
    'nav.investments': '投资',
    'nav.review': '检查确认',
    'header.services': '财务咨询服务',
    'welcome.title': '欢迎来到 XinWealth',
    'welcome.subtitle': '为了给您提供最好的财务建议，我们需要了解您的当前状况。',
    'welcome.button': '开始填写',
    'pdpa.title': 'PDPA 同意书',
    'pdpa.content': '继续操作即表示您同意我们根据马来西亚个人数据保护法 (PDPA) 收集、处理和存储您的个人数据。',
    'pdpa.disclaimer': "请放心，您的数据绝对安全，仅用于财务咨询目的。",
    'pdpa.accept': '我同意并继续',

    'basic.title': '关于您',
    'basic.name': '姓名',
    'basic.salutation': '称呼',
    'basic.email': '邮箱地址',
    'basic.dob': '出生日期',
    'basic.nationality': '国籍',
    'basic.residency': '居住地',
    'basic.marital': '婚姻状况',
    'basic.retirement': '期望退休年龄',
    'basic.employment': '就业状态',
    'basic.tax': '税务状态',
    'basic.occupation': '职业',
    'basic.continue': '继续',
    'basic.back': '返回',

    'income.title': '我们的收入',
    'income.active': '主动收入 (Active Income)',
    'income.monthly': '每月税前薪水',
    'income.salaryLabel': '我的每月税前薪水是：',
    'income.bonus': '年度花红/奖金',
    'income.bonusLabel': '我的年度花红/奖金是',
    'income.passive': '被动收入 (Passive Income)',
    'income.rental': '租金收入',
    'income.rentalOpt': '我拥有出租房产',
    'income.dividend': '股息收入',
    'income.dividendOpt': '我拥有股息/红利',
    'income.other': '其他收入',
    'income.otherOpt': '其他收入类型',
    'income.add': '添加',
    'income.addBtn': '添加收入',
    'income.addMore': '添加更多收入',
    'income.amount': '金额',
    'income.desc': '描述',
    
    'assets.title': '我们的资产',
    'assets.liquid': '我的储蓄',
    'assets.savings': '我的储蓄价值为',
    'assets.epf': '公积金 (EPF)',
    'assets.epf.account1': 'Account 1 (Akaun Persaraan)',
    'assets.epf.account2': 'Account 2 (Akaun Sejahtera)',
    'assets.epf.account3': 'Account 3 (Akaun Fleksibel)',
    'assets.selectAll': '请选择所有适用项',
    'assets.properties': '我拥有房产',
    'assets.vehicles': '我拥有交通工具',
    'assets.others': '其他资产',
    'assets.add': '添加资产',
    'assets.addBtn': '添加资产',
    'assets.value': '价值',

    'liabilities.title': '我的负债',
    'liabilities.mortgages': '房屋贷款',
    'liabilities.car': '汽车贷款',
    'liabilities.study': '教育贷款',
    'liabilities.interest': '纯利息贷款',
    'liabilities.renovation': '装修贷款',
    'liabilities.others': '其他贷款',
    'liabilities.add': '添加贷款',
    'liabilities.addBtn': '添加贷款',
    'liabilities.balance': '未结清余额',

    'expenses.title': '我们的开销',
    'expenses.household': '家庭开销 (Household)',
    'expenses.transport': '交通开销 (Transportation)',
    'expenses.dependants': '受抚养人 (Dependants)',
    'expenses.personal': '个人开销 (Personal)',
    'expenses.misc': '杂项 (Miscellaneous)',
    'expenses.others': '其他开销 (Other Expenses)',
    'expenses.add': '添加开销',
    'expenses.type': '类型',
    'expenses.info': '如果您之前已经提供了贷款详情，贷款还款记录将会自动生成，无需在此作为开销重复填写。',

    'investments.title': '我的投资',
    'investments.etf': '交易所交易基金 (ETF)',
    'investments.bonds': '债券 (Bonds)',
    'investments.stocks': '股票与股份 (Stocks & Shares)',
    'investments.unit': '单位信托 (Unit Trusts)',
    'investments.unitTrusts': '单位信托 (Unit Trusts)',
    'investments.fd': '定期存款 (Fixed Deposits)',
    'investments.fixedDeposits': '定期存款 (Fixed Deposits)',
    'investments.forex': '外汇 (Foreign Exchange)',
    'investments.money': '货币市场 (Money Market)',
    'investments.others': '其他投资 (Other Investment)',
    'investments.other': '其他投资 (Other Investment)',
    'investments.add': '添加投资',
    'investments.addBtn': '添加投资',

    'review.title': '检查确认',
    'review.subtitle': "提交前，请最后检查您的资料是否正确！",
    'review.profile': '个人资料',
    'review.income': '收入',
    'review.assets': '资产',
    'review.liabilities': '负债',
    'review.expenses': '开销',
    'review.investments': '投资',
    'review.edit': '[修改]',
    'review.editDetails': '[修改]',
    'review.total': '总计',
    'review.gross': '总收入',
    'review.grossIncome': '总收入',
    'review.bonus': '花红/奖金',
    'review.nodata': '暂无数据。',
    'review.noData': '暂无数据。',
    'review.hiddenLabel': '为节省空间，已隐藏详细{0}记录。请点击“修改”查看。',
    'review.hiddenDetails': '为节省空间，已隐藏详细记录。请点击“修改”查看。',
    'review.confirm': '确认提交',
    
    'common.required': '必填',
    'common.max100': '最多 100 个字符',
    'common.maxChars': '最多 100 个字符',
    'common.rm': 'RM',
    'common.month': '/月',
    'common.year': '/年',
    'common.perMonth': '/月',
    'common.perYear': '/年',
    'common.delete': '删除',
    'common.value': '价值',
    'common.description': '描述',
    'common.expand': '展开',
    'common.collapse': '收起',
    'common.selectAll': '请选择所有适用项'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string, ...args: string[]): string => {
    let str = translations[language][key] || key;
    args.forEach((arg, index) => {
      str = str.replace(`{${index}}`, arg);
    });
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
