-- GENERATED FILE — do not edit.
-- Source: supabase/functions/_shared/taxonomy/cashflow.ts
-- Rebuild: npx tsx scripts/build-category-seed.ts
-- Upserts every current category. Legacy codes are retired in 20260923000003.
insert into public.cashflow_categories
  (code, label, label_zh, direction, is_system, sort_order, category_group, wealth_effect,
   recurrence, fixed_variable, need_want, link_to, auto_generated, is_active)
values
  ('salary_basic', 'Basic salary (gross)', '基本薪水', 'inflow', true, 10, 'I1', 'income', 'recurring', null, null, 'none', false, true),
  ('fixed_allowance', 'Fixed allowance', '固定津贴', 'inflow', true, 20, 'I1', 'income', 'recurring', null, null, 'none', false, true),
  ('overtime', 'Overtime pay', '加班费', 'inflow', true, 30, 'I1', 'income', 'recurring', null, null, 'none', false, true),
  ('bonus', 'Bonus', '花红/奖金', 'inflow', true, 40, 'I1', 'income', 'irregular', null, null, 'none', false, true),
  ('commission', 'Commission / referral fee', '佣金/介绍费', 'inflow', true, 50, 'I1', 'income', 'recurring', null, null, 'none', false, true),
  ('director_fee', 'Director / advisory / professional fee', '董事费/顾问费/专业费', 'inflow', true, 60, 'I1', 'income', 'recurring', null, null, 'none', false, true),
  ('business_income', 'Business / self-employed net income', '生意/自雇净收入', 'inflow', true, 70, 'I1', 'income', 'recurring', null, null, 'none', false, true),
  ('side_income', 'Side income', '副业/兼职', 'inflow', true, 80, 'I1', 'income', 'recurring', null, null, 'none', false, true),
  ('employer_epf', 'Employer EPF contribution', '雇主公积金供款', 'inflow', true, 90, 'I1', 'income', 'recurring', null, null, 'asset', true, true),
  ('active_income_other', 'Other active income', '其他主动收入', 'inflow', true, 100, 'I1', 'income', 'recurring', null, null, 'none', false, true),
  ('rental_income', 'Rental income', '租金收入', 'inflow', true, 110, 'I2', 'income', 'recurring', null, null, 'asset', false, true),
  ('dividend_company', 'Dividend from own company', '自家公司股息', 'inflow', true, 120, 'I2', 'income', 'recurring', null, null, 'asset', false, true),
  ('dividend_investment', 'Investment dividend / distribution', '投资股息/基金派息', 'inflow', true, 130, 'I2', 'income', 'recurring', null, null, 'asset', false, true),
  ('interest_income', 'Interest income', '利息收入', 'inflow', true, 140, 'I2', 'income', 'recurring', null, null, 'asset', false, true),
  ('royalty', 'Royalty / licensing', '版税/授权费', 'inflow', true, 150, 'I2', 'income', 'recurring', null, null, 'none', false, true),
  ('pension_annuity', 'Pension / annuity', '退休金/年金', 'inflow', true, 160, 'I2', 'income', 'recurring', null, null, 'none', false, true),
  ('policy_cash_payout', 'Policy cash payout / survival benefit', '保单生存金/现金红利', 'inflow', true, 170, 'I2', 'income', 'recurring', null, null, 'policy', false, true),
  ('passive_income_other', 'Other passive income', '其他被动收入', 'inflow', true, 180, 'I2', 'income', 'recurring', null, null, 'none', false, true),
  ('government_aid', 'Government aid (STR etc.)', '政府援助', 'inflow', true, 190, 'I3', 'income', 'one_off', null, null, 'none', false, true),
  ('family_support_in', 'Family support received', '家人给的生活费', 'inflow', true, 200, 'I3', 'income', 'recurring', null, null, 'none', false, true),
  ('gift_inheritance', 'Gift / inheritance', '赠与/遗产', 'inflow', true, 210, 'I3', 'income', 'one_off', null, null, 'none', false, true),
  ('insurance_claim', 'Insurance claim payout', '保险理赔', 'inflow', true, 220, 'I3', 'income', 'one_off', null, null, 'policy', false, true),
  ('policy_surrender_maturity', 'Policy surrender / maturity proceeds', '保单退保/满期所得', 'inflow', true, 230, 'I3', 'income', 'one_off', null, null, 'policy', false, true),
  ('tax_refund', 'Tax refund', '退税', 'inflow', true, 240, 'I3', 'income', 'one_off', null, null, 'none', false, true),
  ('other_income', 'Other income', '其他收入', 'inflow', true, 250, 'I3', 'income', 'one_off', null, null, 'none', false, true),
  ('asset_sale', 'Asset sale proceeds', '出售资产所得', 'inflow', true, 260, 'I4', 'transfer', 'one_off', null, null, 'asset', false, true),
  ('savings_withdrawal', 'Withdrawal from savings / FD / investments', '从储蓄/定存/投资提取', 'inflow', true, 270, 'I4', 'transfer', 'one_off', null, null, 'asset', false, true),
  ('epf_withdrawal', 'EPF withdrawal', '公积金提取', 'inflow', true, 280, 'I4', 'transfer', 'one_off', null, null, 'asset', false, true),
  ('loan_drawdown', 'Loan drawdown', '贷款拨款', 'inflow', true, 290, 'I4', 'transfer', 'one_off', null, null, 'liability', false, true),
  ('borrowing_family', 'Borrowing from family / friends', '向亲友借钱', 'inflow', true, 300, 'I4', 'transfer', 'one_off', null, null, 'liability', false, true),
  ('to_savings', 'Transfer to savings / emergency fund', '转入储蓄/紧急基金', 'outflow', true, 310, 'O1', 'transfer', 'recurring', 'fixed', null, 'asset', false, true),
  ('fd_placement', 'Fixed deposit placement', '存定期', 'outflow', true, 320, 'O1', 'transfer', 'recurring', 'fixed', null, 'asset', false, true),
  ('unit_trust_contribution', 'Unit trust contribution', '单位信托供款', 'outflow', true, 330, 'O1', 'transfer', 'recurring', 'fixed', null, 'asset', false, true),
  ('stock_etf_purchase', 'Stock / ETF purchase', '股票/ETF 买入', 'outflow', true, 340, 'O1', 'transfer', 'recurring', 'variable', null, 'asset', false, true),
  ('asnb_contribution', 'ASB / ASNB contribution', 'ASB/ASNB 存入', 'outflow', true, 350, 'O1', 'transfer', 'recurring', 'fixed', null, 'asset', false, true),
  ('tabung_haji', 'Tabung Haji deposit', '朝圣基金存入', 'outflow', true, 360, 'O1', 'transfer', 'recurring', 'fixed', null, 'asset', false, true),
  ('gold_purchase', 'Gold / precious metals', '黄金/贵金属', 'outflow', true, 370, 'O1', 'transfer', 'recurring', 'variable', null, 'asset', false, true),
  ('crypto_purchase', 'Crypto purchase', '加密货币', 'outflow', true, 380, 'O1', 'transfer', 'recurring', 'variable', null, 'asset', false, true),
  ('prs_contribution', 'PRS contribution', 'PRS 供款', 'outflow', true, 390, 'O1', 'transfer', 'recurring', 'fixed', null, 'asset', false, true),
  ('epf_voluntary', 'EPF voluntary contribution (i-Saraan)', 'EPF 自愿供款', 'outflow', true, 400, 'O1', 'transfer', 'recurring', 'fixed', null, 'asset', false, true),
  ('epf_employee', 'Employee EPF contribution', '雇员 EPF 供款', 'outflow', true, 410, 'O1', 'transfer', 'recurring', 'fixed', null, 'asset', true, true),
  ('sspn', 'SSPN education savings', 'SSPN 教育储蓄', 'outflow', true, 420, 'O1', 'transfer', 'recurring', 'fixed', null, 'asset', false, true),
  ('business_capital', 'Business capital injection', '注资生意', 'outflow', true, 430, 'O1', 'transfer', 'one_off', 'variable', null, 'asset', false, true),
  ('lend_out', 'Lending to others', '借钱给别人', 'outflow', true, 440, 'O1', 'transfer', 'one_off', 'variable', null, 'asset', false, true),
  ('asset_purchase', 'Asset purchase / down payment', '购置资产首付/全款', 'outflow', true, 450, 'O1', 'transfer', 'one_off', 'variable', null, 'asset', false, true),
  ('investment_other', 'Other saving & investing', '其他储蓄投资', 'outflow', true, 460, 'O1', 'transfer', 'recurring', 'fixed', null, 'asset', false, true),
  ('mortgage_installment', 'Mortgage installment', '房贷月供', 'outflow', true, 470, 'O2', 'split', 'recurring', 'fixed', null, 'liability', true, true),
  ('car_installment', 'Car loan (hire purchase) installment', '车贷月供', 'outflow', true, 480, 'O2', 'split', 'recurring', 'fixed', null, 'liability', true, true),
  ('personal_loan_installment', 'Personal loan installment', '个人贷款月供', 'outflow', true, 490, 'O2', 'split', 'recurring', 'fixed', null, 'liability', true, true),
  ('study_loan_installment', 'Study loan (PTPTN) installment', '教育贷款月供', 'outflow', true, 500, 'O2', 'split', 'recurring', 'fixed', null, 'liability', true, true),
  ('renovation_loan_installment', 'Renovation loan installment', '装修贷款月供', 'outflow', true, 510, 'O2', 'split', 'recurring', 'fixed', null, 'liability', true, true),
  ('asb_financing_installment', 'ASB financing installment', 'ASB 贷款月供', 'outflow', true, 520, 'O2', 'split', 'recurring', 'fixed', null, 'liability', true, true),
  ('business_loan_installment', 'Business loan installment', '生意贷款月供', 'outflow', true, 530, 'O2', 'split', 'recurring', 'fixed', null, 'liability', true, true),
  ('bnpl_payment', 'BNPL payment', '先买后付还款', 'outflow', true, 540, 'O2', 'split', 'recurring', 'fixed', null, 'liability', true, true),
  ('family_loan_repayment', 'Family / friend loan repayment', '还亲友借款', 'outflow', true, 550, 'O2', 'split', 'recurring', 'fixed', null, 'liability', true, true),
  ('debt_other', 'Other debt repayment', '其他还款', 'outflow', true, 560, 'O2', 'split', 'recurring', 'fixed', null, 'liability', false, true),
  ('credit_card_payment', 'Credit card payment', '信用卡还款', 'outflow', true, 570, 'O2', 'transfer', 'recurring', 'variable', null, 'liability', false, true),
  ('finance_charges', 'Finance charges', '利息/逾期费/银行手续费', 'outflow', true, 580, 'O2', 'expense', 'recurring', 'variable', null, 'liability', false, true),
  ('share_margin_interest', 'Share margin interest', '股票融资利息', 'outflow', true, 590, 'O2', 'expense', 'recurring', 'variable', null, 'liability', false, true),
  ('life_takaful', 'Life / family takaful', '人寿/家庭保障', 'outflow', true, 600, 'O3', 'expense', 'recurring', 'fixed', null, 'policy', true, true),
  ('medical_card', 'Medical card', '医药卡', 'outflow', true, 610, 'O3', 'expense', 'recurring', 'fixed', null, 'policy', true, true),
  ('critical_illness', 'Critical illness', '危疾', 'outflow', true, 620, 'O3', 'expense', 'recurring', 'fixed', null, 'policy', true, true),
  ('personal_accident', 'Personal accident', '个人意外', 'outflow', true, 630, 'O3', 'expense', 'recurring', 'fixed', null, 'policy', true, true),
  ('savings_plan_premium', 'Savings / investment-linked plan premium', '储蓄型/投资型保单保费', 'outflow', true, 640, 'O3', 'expense', 'recurring', 'fixed', null, 'policy', true, true),
  ('protection_other', 'Other premiums', '其他保费', 'outflow', true, 650, 'O3', 'expense', 'recurring', 'fixed', null, 'policy', false, true),
  ('rent', 'Rent', '房租', 'outflow', true, 660, 'O4', 'expense', 'recurring', 'fixed', 'need', 'none', false, true),
  ('maintenance_fee', 'Maintenance fee & sinking fund', '管理费+偿债基金', 'outflow', true, 670, 'O4', 'expense', 'recurring', 'fixed', 'need', 'asset', false, true),
  ('quit_rent_assessment', 'Quit rent & assessment tax', '地税/门牌税', 'outflow', true, 680, 'O4', 'expense', 'irregular', 'fixed', 'need', 'asset', false, true),
  ('home_insurance', 'Houseowner / fire insurance', '房屋火险', 'outflow', true, 690, 'O4', 'expense', 'irregular', 'fixed', 'need', 'asset', false, true),
  ('utilities', 'Utilities', '水电/排污/燃气', 'outflow', true, 700, 'O4', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('telco', 'Phone, internet, TV & streaming', '电话/网络/电视/串流', 'outflow', true, 710, 'O4', 'expense', 'recurring', 'fixed', 'need', 'none', false, true),
  ('home_repair', 'Home repair & upkeep', '房屋维修保养', 'outflow', true, 720, 'O4', 'expense', 'irregular', 'variable', 'need', 'asset', false, true),
  ('household_help', 'Domestic helper salary & levy', '女佣薪水/准证', 'outflow', true, 730, 'O4', 'expense', 'recurring', 'fixed', 'want', 'none', false, true),
  ('housing_other', 'Other housing', '其他住房开销', 'outflow', true, 740, 'O4', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('fuel', 'Fuel', '油费', 'outflow', true, 750, 'O5', 'expense', 'recurring', 'variable', 'need', 'asset', false, true),
  ('toll_parking', 'Tolls & parking', '过路费/停车', 'outflow', true, 760, 'O5', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('public_transport_ehailing', 'Public transport & e-hailing', '公共交通/Grab', 'outflow', true, 770, 'O5', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('road_tax', 'Road tax', '路税', 'outflow', true, 780, 'O5', 'expense', 'irregular', 'fixed', 'need', 'asset', false, true),
  ('motor_insurance', 'Motor insurance', '汽车保险', 'outflow', true, 790, 'O5', 'expense', 'irregular', 'fixed', 'need', 'asset', false, true),
  ('car_service_repair', 'Car servicing & repair', '保养维修', 'outflow', true, 800, 'O5', 'expense', 'irregular', 'variable', 'need', 'asset', false, true),
  ('transport_other', 'Other transport', '其他交通', 'outflow', true, 810, 'O5', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('groceries', 'Groceries', '杂货/菜市', 'outflow', true, 820, 'O6', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('dining_out', 'Dining out & delivery', '外食/外卖', 'outflow', true, 830, 'O6', 'expense', 'recurring', 'variable', 'want', 'none', false, true),
  ('personal_care', 'Personal care', '个人护理/理发/美容', 'outflow', true, 840, 'O6', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('clothing', 'Clothing', '服装', 'outflow', true, 850, 'O6', 'expense', 'recurring', 'variable', 'want', 'none', false, true),
  ('health_medical', 'Medical, dental & optical (out of pocket)', '看病/药物/牙科/眼科', 'outflow', true, 860, 'O6', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('fitness', 'Fitness & sports', '健身/运动', 'outflow', true, 870, 'O6', 'expense', 'recurring', 'variable', 'want', 'none', false, true),
  ('living_other', 'Other daily living', '其他日常', 'outflow', true, 880, 'O6', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('childcare', 'Childcare', '托儿/保姆', 'outflow', true, 890, 'O7', 'expense', 'recurring', 'fixed', 'need', 'none', false, true),
  ('school_fees', 'School fees', '学费', 'outflow', true, 900, 'O7', 'expense', 'recurring', 'fixed', 'need', 'none', false, true),
  ('tuition_enrichment', 'Tuition & enrichment', '补习/才艺班', 'outflow', true, 910, 'O7', 'expense', 'recurring', 'fixed', 'want', 'none', false, true),
  ('child_expenses', 'Children''s daily expenses', '孩子日常开销', 'outflow', true, 920, 'O7', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('parents_allowance', 'Allowance to parents', '父母生活费', 'outflow', true, 930, 'O7', 'expense', 'recurring', 'fixed', 'need', 'none', false, true),
  ('other_dependants', 'Other dependants', '其他受养人', 'outflow', true, 940, 'O7', 'expense', 'recurring', 'fixed', 'need', 'none', false, true),
  ('self_education', 'Self-education', '自我进修', 'outflow', true, 950, 'O7', 'expense', 'recurring', 'variable', 'want', 'none', false, true),
  ('pet_care', 'Pet care', '宠物', 'outflow', true, 960, 'O7', 'expense', 'recurring', 'variable', 'want', 'none', false, true),
  ('family_other', 'Other family', '其他家庭开销', 'outflow', true, 970, 'O7', 'expense', 'recurring', 'variable', 'need', 'none', false, true),
  ('entertainment', 'Entertainment', '娱乐', 'outflow', true, 980, 'O8', 'expense', 'recurring', 'variable', 'want', 'none', false, true),
  ('travel', 'Travel', '旅游', 'outflow', true, 990, 'O8', 'expense', 'irregular', 'variable', 'want', 'none', false, true),
  ('hobbies', 'Hobbies', '兴趣爱好', 'outflow', true, 1000, 'O8', 'expense', 'recurring', 'variable', 'want', 'none', false, true),
  ('subscriptions', 'Subscriptions', '订阅服务', 'outflow', true, 1010, 'O8', 'expense', 'recurring', 'fixed', 'want', 'none', false, true),
  ('shopping_gadgets', 'Shopping & gadgets', '购物/电子产品', 'outflow', true, 1020, 'O8', 'expense', 'recurring', 'variable', 'want', 'none', false, true),
  ('lifestyle_other', 'Other lifestyle', '其他生活方式', 'outflow', true, 1030, 'O8', 'expense', 'recurring', 'variable', 'want', 'none', false, true),
  ('income_tax', 'Income tax (PCB / CP500)', '所得税', 'outflow', true, 1040, 'O9', 'expense', 'recurring', 'fixed', null, 'none', false, true),
  ('socso_eis', 'SOCSO / EIS', 'SOCSO/EIS', 'outflow', true, 1050, 'O9', 'expense', 'recurring', 'fixed', null, 'none', true, true),
  ('zakat_tithe', 'Zakat / tithe', '天课/什一奉献', 'outflow', true, 1060, 'O9', 'expense', 'recurring', 'fixed', null, 'none', false, true),
  ('donations', 'Donations & charity', '捐款/慈善', 'outflow', true, 1070, 'O9', 'expense', 'recurring', 'variable', null, 'none', false, true),
  ('festive_angpao', 'Festive ang pao / duit raya', '节庆红包', 'outflow', true, 1080, 'O9', 'expense', 'irregular', 'variable', null, 'none', false, true),
  ('gifts_social', 'Gifts & social obligations', '礼物/红白包', 'outflow', true, 1090, 'O9', 'expense', 'recurring', 'variable', null, 'none', false, true),
  ('obligation_other', 'Other obligations', '其他义务', 'outflow', true, 1100, 'O9', 'expense', 'recurring', 'variable', null, 'none', false, true),
  ('professional_fees', 'Professional fees', '专业服务费', 'outflow', true, 1110, 'O10', 'expense', 'recurring', 'variable', null, 'none', false, true),
  ('other_expense', 'Other expense', '其他支出', 'outflow', true, 1120, 'O10', 'expense', 'recurring', 'variable', null, 'none', false, true)
on conflict (code) do update set
  label = excluded.label,
  label_zh = excluded.label_zh,
  direction = excluded.direction,
  sort_order = excluded.sort_order,
  category_group = excluded.category_group,
  wealth_effect = excluded.wealth_effect,
  recurrence = excluded.recurrence,
  fixed_variable = excluded.fixed_variable,
  need_want = excluded.need_want,
  link_to = excluded.link_to,
  auto_generated = excluded.auto_generated,
  is_active = excluded.is_active;
